name: Dependency Review

# trigger on main branch but only if specific files or paths have changes
on:
  pull_request:
    branches:
      - main
    paths:
      # only check if a manifest file has changed
      - "Dockerfile"
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/**"

# ensures only one run of the workflow happens per branch or per run (if not associated with a branch)
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v3
        with:
          # this will fail if the security advisory databse has a minimum level of "fail-on-severity" value or higher.
          fail-on-severity: low
          comment-summary-in-pr: "on-failure"
          # Deny specific packages
          deny-packages: "pkg:pypi/pycrypto"
          # Deny all copy-left licenses
          deny-licenses: "GPL-1.0, GPL-2.0, GPL-3.0, AGPL-1.0, AGPL-3.0, LGPL-2.1, LGPL-3.0, MPL-2.0, CDDL-1.0, EPL-1.0"
          # Error out if there are unknown licenese detected. Note: There is no allow list if this fails.
          deny-unknown-license: true
          # Allow list of packages that may have failed a license check but are explicitly OK.
          allow-packages: "pkg:pypi/erpnext, pkg:pypi/flask-oidc-ex"
